### PR TITLE
Android Studio 4.0 + CI on pull request

### PR DESCRIPTION
**Pull request by hannesa2**
* Android Studio 4.0
* update libraries
* remove maven publish (please use jitpack.io)
* Gradle 5.0
* pull request check on CI

### CODE REVIEW

**Comment by hannesa2** [comment]
Ahhh, you have to enable Github actions to build with it

**Comment by hannesa2** [comment]
your Gradle jar is too old to verify

**Comment by MKergall** [comment]
Oh, sounds good, thanks a lot. I will try that soon.

**Comment by MKergall** [comment]
"Gradle sync failed: This version of Android Studio cannot open this project, please retry with Android Studio 4.0 or newer."

=> OMG: this only works with Android 4.0 ?! This is endless!

**Comment by hannesa2** [comment]
> => OMG: this only works with Android 4.0 ?! This is endless!

Don't be worry, now you have a modern repo with CI check.

**Comment by MKergall** [comment]
OK, forget my previous negative comment - update to Android 4.0 was straightforward. And now... it works! 
There was an issue in OSMBonusPackTuto: no map - was due to lack of permissions handling. Now fixed and pushed.

**Comment by hannesa2** [comment]
May I suggest you to set a new tag for a new release ?

**Comment by MKergall** [comment]
Yes I will, when I will have enough time to ensure everything is fine.

**Pull request merged**
