### PR TITLE
OSMBonusPack, improvements

### PR DESCRIPTION
**Pull request by jurrick**
This request contains:
* upgrading versions for dependency libraries;
* customizing translations for road directions (default languages located in `res/values/strings.xml`);
* replacing Apache Client to OkHttpClient.

### CODE REVIEW

**Comment by MKergall** [comment]
Same error on KmlDocument.parseKMLStream.

**Comment by jurrick** [comment]
Thank you for testing.

Yes, I removed `BonusPackHelper.requestStringFromPost`, because it isn't used in project (i searched it on the whole project).

I also will try to see and edit problems above.

**Comment by jurrick** [comment]
I'm just searched problem above with **GoogleRoadManager**, and I found a solution:

http://stackoverflow.com/questions/24465427/okhttp-response-xmlpullparser

Now, I can't test it because of the deadline on the project :-), but the solution to the above should help.

**Comment by MKergall** [comment]
OK, found. You did: 
        content = response.body().string();
        stream = response.body().byteStream();

So stream was empty because response.body().string() "consumed" the whole content. 
Fix now pushed.

**Pull request merged**
