### PR TITLE
add maven support

### LINKED ISSUE #108: Maven Central or jCenter Publication
```
It would be nice to have an easy-accessible dependency. If you are not familiar 
with it, this change will allow a very nice dependency resolving mechanism for 
this library: 
https://developer.android.com/tools/building/configuring-gradle.html

Also, this will allow you to remove binaries from the source code (the 'libs' 
directory). It will require to migrate the library to Gradle or Maven though.
```

Original issue reported on code.google.com by `artur.dr...@gmail.com` on 26 Jan 2015 at 3:34

### LINKED ISSUE #116: Migrate to GitHub
```
Are there any plans to migrate this project to GitHub?
```

Original issue reported on code.google.com by `ziem1...@gmail.com` on 25 Mar 2015 at 8:37

### PR DESCRIPTION
**Pull request by larsgrefer**
this will add the `:install` task to the library projects which will install the `aar` files in the local maven repo

this should also enable you to use https://jitpack.io/#MKergall/osmbonuspack in order to fix #108 and fix #116

### CODE REVIEW

**Comment by spyhunter99** [comment]
10+

**Comment by larsgrefer** [comment]
@MKergall Can you please review this.
I'd love to be able to use jitpack.

**Comment by MKergall** [comment]
Done. 
JitPack stuff seems great (if we can avoid spending days to publish on Maven Central). 
Now, how users are supposed to configure their build.gradle? Is the PR #176 the right explanation?

**Comment by larsgrefer** [comment]
The correct dependency declarations are:
```gradle
dependencies {
    compile 'com.github.MKergall.osmbonuspack:OSMBonusPack:<version>'
    compile 'com.github.MKergall.osmbonuspack:MapsForgeForOsmdroid:<version>'
}
```
Where `<version>` is a git tag or commit hash

I've tested with version 2e8bca20f7 (the commit of the merge of this PR): https://jitpack.io/com/github/MKergall/osmbonuspack/2e8bca20f7/build.log

**Comment by spyhunter99** [comment]
I highly suggest you stick to the standard maven versioning scheme. using the git hash tag is about as user friendly as a thorn bush

**Comment by larsgrefer** [comment]
@spyhunter99 I agree, but at the moment there is no release containing this PR

**Comment by spyhunter99** [comment]
So 5.5-SNAPSHOT then

**Comment by larsgrefer** [comment]
If i declare "5.5-SNAPSHOT" as dependency version in my project, my builds won't be reproducible.

**Comment by MKergall** [comment]
Release v5.6 has just been published. JitPack status for this version is OK. 
Included in the Tuto project: 

    compile 'com.github.MKergall.osmbonuspack:OSMBonusPack:v5.6'

I got some non-reproducible build errors, which disapeared with a full clean. 
Hope this solution is stable...

**Comment by spyhunter99** [comment]
We have to declare the version number of osmbonus packs gradle files.
Usually it's a property in gradle.properties. Build osmbonuspack via
'gradle install' to install to maven local.
Then in your project, reference mavenLocal as a repo, and the appropriate
version number for osmbonuspack.

**Comment by larsgrefer** [comment]
@spyhunter99 As user of this library I don't want to build it myself in order to get it to my local maven repo. I wan't to get the already built artifact from an central repository (mavenCentral, jcenter or jitpack).

About the version numbers:
Every gradle project has the property `version` which is used as version for maven artifacts.
- The default value is `unspecified`.
- Usually you overwrite this in your build.gradle.
- When jitpack runs the build it overrides both of the above with an command-line param to whatever version you requested (commit-hash, tag-name, *-SNAPSHOT):

`./gradlew clean -Pgroup=com.github.MKergall -Pversion=2e8bca20f7 -xtest -xlint install`

So when @MKergall creates a release here with the tag `v5.6` the version number on jipack will be `v5.6` (regardless of what is specified in the build.gradle or not)

**Comment by spyhunter99** [comment]
i agree. publishing it somewhere is a good thing. versioning locally is
useful for testing modifications to the library.

**Comment by larsgrefer** [comment]
If you want jitpack-like versions when you build on your local machine (or elsewere) try this little snippet:

https://gist.github.com/larsgrefer/30b36bd74b162631f143#file-git-version-gradle

**Comment by spyhunter99** [comment]
http://stackoverflow.com/questions/6122252/gradle-alternate-to-mvn-install
simple solution
apply plugin: 'maven'

group = "org.osmdroid.bonuspack"
version = "5.5-SNAPSHOT"

added to the AAR script

then

gradle install

**Comment by larsgrefer** [comment]
@spyhunter99 the `maven` plugin does not work for android projects (just vor java ones). We need this one: https://github.com/dcendents/android-maven-gradle-plugin

With the snippet i posted before gradle calculates the `version` using git tags (currentTag or lastTag-SNAPSHOT) so you don't need to hardcode the version in the `build.gradle`. (Because the DRY-Principle is violated if the version ist specified in the build.gradle AND a git tag)

**Comment by larsgrefer** [comment]
@spyhunter99 you might want to have a look at #182

**Comment by spyhunter99** [comment]
I'm content. I was just throwing in two cents and was apparently wrong
anyhow. Gradle is almost too flexible, leading to many people doing things
in many different ways, all to accomplish the same task.

**Pull request merged**
