### PR TITLE
Update mapsforge libs

### PR DESCRIPTION
**Pull request by hannesa2**

### CODE REVIEW

**Comment by MKergall** [comment]
Before I merge: 
- did you test it? 
- implementation 'org.osmdroid:osmdroid-mapsforge:6.1.4@aar' => Not 6.1.6 ?

**Comment by hannesa2** [comment]
Yes, I did a smoke test

image

but I see this, but I guess, it's not related to this PR

image

**Comment by hannesa2** [comment]
You removed this, why ?

image

**Comment by MKergall** [comment]
?? 
I just pressed "Merge"...

**Pull request merged**
